---
channel: edge
addons:
  signal_messenger:
    repository: TheBlackMini/signal-addon
    target: signal
    image: ghcr.io/theblackmini/signal_messenger/{arch}
  jackett:
    repository: TheBlackMini/jackett-addon
    target: jackett
    image: ghcr.io/theblackmini/jackett/{arch}
