---
channel: edge
addons:
  nextcloud:
    repository: haberda/nextcloud-addon
    target: nextcloud
    image: ghcr.io/haberda/nextcloud/{arch}
  signal_messenger:
    repository: haberda/signal-addon
    target: signal
    image: ghcr.io/haberda/signal_messenger/{arch}
  emby:
    repository: haberda/emby-addon
    target: emby_addon
    image: ghcr.io/haberda/emby/{arch}
