arch:
- aarch64
- amd64
- armv7
backup_exclude:
- '*/cache/'
- '*/logs/'
- '*/transcoding-temp/'
- '*/metadata/'
boot: manual
description: emby media server
devices:
- /dev/dri
- /dev/vchiq
- /dev/video10
- /dev/video11
- /dev/video12
image: ghcr.io/haberda/emby/{arch}
init: false
map:
- share:rw
- media:rw
- ssl:rw
name: emby
options:
  cifspassword: <password>
  cifsusername: <username>
  cifsversion: 3.0
  networkdisks: null
ports:
  1900/udp: 1900
  33791/tcp: 33791
  33796/tcp: 33796
  7359/udp: 7359
  8096/tcp: 8096
  8920/tcp: 8920
ports_description:
  1900/udp: '1900'
  33791/tcp: external http webui
  33796/tcp: external https webui
  7359/udp: '7359'
  8096/tcp: http webui
  8920/tcp: https webui
privileged:
- SYS_ADMIN
- DAC_READ_SEARCH
schema:
  cifspassword: str
  cifsusername: str
  cifsversion: list(3.0|2.1|2.0|1.0)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  networkdisks:
  - str
slug: emby
startup: system
url: https://github.com/haberda/emby-addon
version: 6ad6e9c
webui: http://[HOST]:[PORT:8096]
