arch:
- armv7
- aarch64
- amd64
backup_exclude:
- '*.txt'
description: Jackett for Home Assistant
devices:
- /dev/net/tun
environment:
  LOG_FORMAT: '{LEVEL}: {MESSAGE}'
hassio_api: true
image: ghcr.io/haberda/jackett/{arch}
init: false
map:
- config:rw
- media:rw
- share:rw
- ssl
name: Jackett
options:
  local_network: 192.168.1.0/24
  log_level: info
  openvpn_config: null
  openvpn_enabled: false
  openvpn_password: null
  openvpn_username: null
panel_icon: mdi:coat-rack
ports:
  9117/tcp: 9117
ports_description:
  9117/tcp: Web UI port
privileged:
- NET_ADMIN
schema:
  local_network: str
  log_level: match(^(trace|debug|info|notice|warning|error|fatal)$)
  openvpn_config: str
  openvpn_enabled: bool
  openvpn_password: str
  openvpn_username: str
slug: jackett
startup: services
url: https://github.com/haberda/jackett-addon
version: ee21487
webui: http://[HOST]:[PORT:9117]
